config/urls.py
from django.contrib import admin
from django.urls import path,include
import fenrir.views



urlpatterns = [
    path('',include("fenrir.urls")),
    path('admin/', admin.site.urls),
]



fenrir/urls.py
from django.urls import path
from . import views

app_name = "fenrir"
urlpatterns = [
  path("",views.TopView.as_view(),name="search_input"),
  path("search_results/", views.SearchResultsView.as_view(), name="search_results"),
  path('restaurant_detail/<str:restaurant_id>/', views.RestaurantDetailView.as_view(), name='restaurant_detail'),
  path("question/", views.questionView.as_view(), name="question"),
  path("use/", views.useView.as_view(), name="use"),
]

fenrir/models.py
# restaurants/models.py

from django.db import models

class Restaurant(models.Model):
    id = models.CharField(max_length=255, primary_key=True)
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    access = models.TextField(blank=True, null=True)
    business_hours = models.TextField(blank=True, null=True)
    thumbnail_image = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.name

fenrir/views.py
from django.views.generic import TemplateView, ListView
from django.shortcuts import get_object_or_404
from fenrir.models import Restaurant
import requests as req

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
class TopView(TemplateView):
    template_name = "fenrir/search_input.html"

class questionView(TemplateView):
    template_name = "fenrir/question.html"

class useView(TemplateView):
    template_name = "fenrir/use.html"

class SearchResultsView(ListView):
    model = Restaurant
    template_name = "fenrir/search_results.html"
    context_object_name = "restaurants"
    paginate_by = 10

    def get_queryset(self):
        user_location = {
            'latitude': float(self.request.GET.get('latitude', 35.6895)),
            'longitude': float(self.request.GET.get('longitude', 139.6917)),
        }
        radius = int(self.request.GET.get('radius', 500))
        search_range = self.get_search_range(radius)
        all_restaurants = self.get_all_restaurants(user_location, search_range)

        if not all_restaurants:
            return []

        return all_restaurants

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ページネーションの処理を追加
        paginator = Paginator(self.object_list, self.paginate_by)
        page = self.request.GET.get('page', 1)

        try:
            restaurants = paginator.page(page)
        except PageNotAnInteger:
            restaurants = paginator.page(1)
        except EmptyPage:
            restaurants = paginator.page(paginator.num_pages)

        context['restaurants'] = restaurants

         # ユーザの位置情報をテンプレートのコンテキストに渡す
        context['user_location'] = {
            'latitude': self.request.GET.get('latitude', 35.6895),
            'longitude': self.request.GET.get('longitude', 139.6917),
        }

        return context
    

    def get_all_restaurants(self, user_location, radius, per_page=10):
        api_key = '7699907c06980421'
        endpoint = 'https://webservice.recruit.co.jp/hotpepper/gourmet/v1/'

        all_restaurants = []
        page = 1

        while True:
            start = (page - 1) * per_page + 1

            params = {
                'key': api_key,
                'lat': user_location['latitude'],
                'lng': user_location['longitude'],
                'range': radius,
                'format': 'json',
                'start': start,
                'count': per_page,
            }

            response = req.get(endpoint, params=params)

            if response.status_code != 200:
                print(f"APIリクエストエラー: {response.status_code}")
                print(response.text)
                return all_restaurants

            data = response.json()

            current_page_restaurants = data.get('results', {}).get('shop', [])
            if not current_page_restaurants:
                break

            for entry in current_page_restaurants:
                restaurant_data = {
                    'id': entry.get('id', ''),
                    'name': entry.get('name', ''),
                    'address': entry.get('address', ''),
                    'access': entry.get('access', ''),
                    'business_hours': entry.get('open', ''),
                    'thumbnail_image': entry.get('photo', {}).get('pc', {}).get('l', ''),
                }

                restaurant = Restaurant(**restaurant_data)
                restaurant.save()
                all_restaurants.append(restaurant)  # 新しいページのデータを追加

            page += 1

        return all_restaurants

    def get_search_range(self, radius):
        if radius <= 300:
            return 1
        elif radius <= 500:
            return 2
        elif radius <= 1000:
            return 3
        elif radius <= 2000:
            return 4
        else:
            return 5

class RestaurantDetailView(TemplateView):
    template_name = "fenrir/restaurant_detail.html"

    model = Restaurant
    template_name = "fenrir/restaurant_detail.html"
    context_object_name = "restaurant"

    def get_object(self, queryset=None):
        restaurant_id = self.kwargs.get('restaurant_id')
        return get_object_or_404(Restaurant, id=restaurant_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['restaurant'] = self.get_object()
        return context


fenrir/templates/fenrir/base.html
{% load static %}

<!-- restaurants/templates/fenrir/base.html -->

<!-- restaurants/templates/fenrir/base.html -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
        crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'fenrir/css/base.css' %}">
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
        }

        header {
            background-color: #343a40;
            color: white;
            padding: 10px 20px;
        }

        nav ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            display: flex;
        }

        nav ul li {
            margin-right: 20px;
        }

        nav ul li:last-child {
            margin-right: 0;
        }

        main {
            padding: 20px;
        }

        footer {
            background-color: #343a40;
            color: white;
            text-align: center;
            padding: 10px;
        }
    </style>
</head>

<body>
    <header class="bg-dark text-white">
        <div class="container">
            <h1 class="font-italic">Fenrir Restaurant App</h1>
            <nav>
                <ul class="nav">
                    <li class="nav-item">
                        <a  href="{% url 'fenrir:search_input' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'fenrir:use' %}">How to use</a>
                    </li>
                    <li class="nav-item">
                        <a  href="{% url 'fenrir:question' %}">Enquiry</a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>

    <main class="container">
        {% block content %}{% endblock %}
    </main>

    <footer class="bg-dark text-white">
        <div class="container">
            <!-- フッターの内容を追加 -->
        </div>
    </footer>

    <!-- ここに共通のJavaScriptファイルやライブラリのリンクを追加 -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

fenrir/templates/fenrir/question.html
{% extends "fenrir/base.html" %}
{% load static %}

{% block content %}
<head>
  <meta charset='UTF-8'>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'fenrir/css/details.css' %}">
</head>

<main class="container">
  <h2>Contact Us</h2>
  <form>
      <div class="form-group">
          <label for="name">Name:</label>
          <input type="text" class="form-control" id="name" name="name" required>
      </div>

      <div class="form-group">
          <label for="email">Email:</label>
          <input type="email" class="form-control" id="email" name="email" required>
      </div>

      <div class="form-group">
          <label for="message">Message:</label>
          <textarea class="form-control" id="message" name="message" rows="4" required></textarea>
      </div>

      <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</main>
{% endblock %}

fenrir/templates/fenrir/restaurant_detail.html
<!-- restaurants/templates/restaurants/restaurant_detail.html -->
{% extends "fenrir/base.html" %}
{% load static %}

{% block content %}
<head>
  <meta charset='UTF-8'>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'fenrir/css/details.css' %}">
</head>

  <h2>{{ restaurant.name }}</h2>
  <h3> 住所</h3><p> {{ restaurant.address }}</p>
  <h3>営業時間</h3><p>{{ restaurant.business_hours }}</p>
  <img src="{{ restaurant.thumbnail_image }}" alt="{{ restaurant.name }}">
  <!-- その他の詳細情報を表示 -->

  <a href="{% url 'fenrir:search_input' %}">検索画面に戻る</a>
{% endblock %}

fenrir/templates/fenrir/seach_input.html
<!-- restaurants/templates/restaurants/search_input.html -->

{% extends "fenrir/base.html" %}

{% block content %}
  <h2>検索条件入力</h2>
  <form method="GET" action="{% url 'fenrir:search_results' %}">
    {% csrf_token %}
    <label for="radius">検索半径（メートル）:</label>
    <input type="number" name="radius" id="radius" value="500" required>
    <button type="submit">検索</button>
  </form>
{% endblock %}

fenrir/templates/fenrir/search_input.html
<!-- restaurants/templates/restaurants/search_input.html -->

{% extends "fenrir/base.html" %}

{% load static %}
{% block content %}

<head>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhg8RBbcrfWT_R3E2dISbpqHtSC7LLUwY&callback=initMap" async defer></script>
  <script src="{% static 'fenrir/js/search_input.js' %}"></script>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  <link rel="stylesheet" type="text/css" href="{% static 'fenrir/css/search_input.css' %}">
</head>

<body>
  <!-- search_input.html -->
 <!-- <button onclick="getCurrentLocation()">現在地を取得</button><br> -->

  
  <label>検索したい場所の入力：<input id="input-address" type="text"></label>
  <button onclick="geocodeAndShowLocation()">登録</button><br>


  <form method="GET" action="{% url 'fenrir:search_results' %}">
    {% csrf_token %}
    <label for="radius">検索半径：</label>
    <input type="number" name="radius" id="radius" value="500" required>
    <input type="hidden" id="latitude" name="latitude" value="{% if user_location.latitude %}{{ user_location.latitude }}{% endif %}">
    <input type="hidden" id="longitude" name="longitude" value="{% if user_location.longitude %}{{ user_location.longitude }}{% endif %}">
    <button type="submit">検索</button>
  </form>

  
  

  <div id="map"></div>

</body>

{% endblock %}

fenrir/templates/fenrir/search_results.html
<!-- restaurants/templates/fenrir/search_results.html -->

{% extends "fenrir/base.html" %}

{% block content %}
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">

  <style>
    h2{
      font-size: 1.5rem;
    }
    .restaurant-card h3 {
      font-size: 1.5rem; /* Adjust the font size to your preference */
    }
    .restaurant-card {
      border: 1px solid #ddd;
      padding: 10px;
      margin: 10px 0;
    }


    .pagination {
      margin-top: 20px;
    }

    .pagination-previous,
    .pagination-next,
    .pagination-link,
    .pagination-ellipsis {
      cursor: pointer;
      padding: 5px;
      margin: 0 2px;
      border: 1px solid #ddd;
      border-radius: 3px;
      text-decoration: none;
      color: #333;
    }

    .pagination-link.is-current {
      background-color: #007bff;
      color: white;
      border: 1px solid #007bff;
    }

    .pagination-link:hover,
    .pagination-previous:hover,
    .pagination-next:hover,
    .pagination-ellipsis:hover {
      background-color: #f5f5f5;
    }
  </style>
</head>
  <h2>検索結果</h2>

  <!-- ページネーションの追加 -->
  <div class="pagination is-centered">
    <a class="pagination-previous" {% if restaurants.has_previous %}href="?page={{ restaurants.previous_page_number }}&latitude={{ user_location.latitude }}&longitude={{ user_location.longitude }}"{% endif %}>前へ</a>
    <a class="pagination-next" {% if restaurants.has_next %}href="?page={{ restaurants.next_page_number }}&latitude={{ user_location.latitude }}&longitude={{ user_location.longitude }}"{% endif %}>次へ</a>
    <ul class="pagination-list">
      {% if restaurants.has_previous %}
        {% if restaurants.previous_page_number != 1 %}
          <li><a class="pagination-link" href="?page=1&latitude={{ user_location.latitude }}&longitude={{ user_location.longitude }}">1</a></li>
          <li><span class="pagination-ellipsis">&hellip;</span></li>
        {% endif %}
        <li><a class="pagination-link" href="?page={{ restaurants.previous_page_number }}&latitude={{ user_location.latitude }}&longitude={{ user_location.longitude }}">{{ restaurants.previous_page_number }}</a></li>
      {% endif %}
      <li><a class="pagination-link is-current" href="?page={{ restaurants.number }}&latitude={{ user_location.latitude }}&longitude={{ user_location.longitude }}">{{ restaurants.number }}</a></li>
      {% if restaurants.has_next %}
        <li><a class="pagination-link" href="?page={{ restaurants.next_page_number }}&latitude={{ user_location.latitude }}&longitude={{ user_location.longitude }}">{{ restaurants.next_page_number }}</a></li>
        {% if restaurants.next_page_number != restaurants.paginator.num_pages %}
          <li><span class="pagination-ellipsis">&hellip;</span></li>
          <li><a class="pagination-link" href="?page={{ restaurants.paginator.num_pages }}&latitude={{ user_location.latitude }}&longitude={{ user_location.longitude }}">{{ restaurants.paginator.num_pages }}</a></li>
        {% endif %}
      {% endif %}
    </ul>
  </div>
  


  {% for restaurant in restaurants %}
    <!-- レストランの表示内容 -->
    <div class="restaurant-card">
        <h3>{{ restaurant.name }}</h3>
        <p>{{ restaurant.address }}</p>
        <p>{{ restaurant.access }}</p>
        <img src="{{ restaurant.thumbnail_image }}" alt="{{ restaurant.name }}">
        <a href="{% url 'fenrir:restaurant_detail' restaurant.id %}">詳細を見る</a>
    </div>
  {% endfor %}


{% endblock %}


fenrir/templates/fenrir/use.html
<!-- HTML (how_to_use.html) -->

{% extends "fenrir/base.html" %}
{% load static %}

{% block content %}
<head>
  <meta charset='UTF-8'>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <style>
    body {
    font-family: 'Arial', sans-serif;
    margin: 0;
    padding: 0;
}

header {
    background-color: #343a40;
    color: white;
    padding: 10px 20px;
}

main {
    padding: 20px;
}

.instruction-card {
    margin-bottom: 30px;
}

.instruction-card img {
    max-width: 100%;
    height: auto;
}

.instruction-card p {
    margin-top: 10px;
}
  </style>
</head>

<main class="container">
  <h2>How to Use</h2>

  <section class="instruction-card">
    <img src="..\static\fenrir\ping\image1.png" alt="Step 1">
    <p>Step 1: 検索したい場所を入力！そのあと登録ボタンをクリック！(ボタンを押すことで位置情報の入力が確定します)
      検索場所周辺の地図が表示されます！</p>
  </section>

  <section class="instruction-card">
    <img src="..\static\fenrir\ping\image2.png" alt="Step 2">
    <p>Step 2:検索半径を入力！自分のいる場所から300ｍ、500ｍ、1000ｍ、2000ｍ、の500ｍ刻みで検索半径を指定できます！</p>
  </section>

  <section class="instruction-card">
    <img src="..\static\fenrir\ping\image3.png" alt="Step 3">
    <p>Step 3:現在地から検索半径以内にある飲食店が表示されます！気になる飲食店は詳細情報を確認してみましょう！</p>
  </section>

  <section class="instruction-card">
    <img src="..\static\fenrir\ping\image4.png" alt="Step 4">
    <p>Step 4:営業時間等の詳細情報が確認出来たらお店へGO！</p>
  </section>
</main>
{% endblock %}